package gg.arch.archflags.resourcepack;

import com.sun.net.httpserver.HttpServer;
import gg.arch.archflags.ArchFlagsPlugin;
import gg.arch.archflags.config.ArchFlagsConfig;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.UUID;
import java.util.concurrent.Executors;
import net.kyori.adventure.resource.ResourcePackInfo;
import net.kyori.adventure.resource.ResourcePackRequest;
import net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer;
import org.bukkit.entity.Player;

/**
 * ArchFlags' own, fully independent Java resource pack -- generated by
 * tools/asset-generator/generate.mjs, embedded in the plugin jar, and sent to each Java player
 * additively (never replacing an already-applied pack, e.g. NxRanks') via the multi-resource-pack
 * protocol (Minecraft 1.20.3+). Never merged into, and never overwrites, NxRanks' pack.
 * <p>
 * The pack must be reachable over HTTP by the player's client. Either point
 * {@code resourcepack.java.url} at an externally-hosted copy (recommended for a real network), or
 * let ArchFlags self-host it via a small embedded HTTP server (default).
 */
public final class JavaResourcePackService {

    /** How the pack is currently being made reachable to players, for /archflags status. */
    public enum DeliveryMode {
        /** {@code resourcepack.java.url} is set -- recommended for a real multi-backend network. */
        EXTERNAL,
        /** ArchFlags' own built-in HTTP server is serving the pack. */
        SELF_HOST,
        /** Sending is off, or misconfigured badly enough that it couldn't start. */
        DISABLED
    }

    private static final UUID PACK_ID = UUID.nameUUIDFromBytes("archflags-java-resourcepack".getBytes(StandardCharsets.UTF_8));
    private static final String EMBEDDED_RESOURCE = "archflags-java-pack.zip";
    private static final String STAGED_FILE_NAME = "ArchFlags-Java.zip";
    private static final String HTTP_PATH = "/ArchFlags-Java.zip";

    private final ArchFlagsPlugin plugin;

    private HttpServer httpServer;
    private volatile byte[] packBytes;
    private volatile String sha1Hex;
    private volatile URI packUri;
    private volatile boolean enabled;
    private volatile DeliveryMode deliveryMode = DeliveryMode.DISABLED;

    public JavaResourcePackService(ArchFlagsPlugin plugin) {
        this.plugin = plugin;
    }

    /** (Re)loads and (re)serves the pack according to current config. Safe to call on reload. */
    public void reload() {
        stop();
        enabled = false;
        deliveryMode = DeliveryMode.DISABLED;
        packUri = null;

        ArchFlagsConfig cfg = plugin.archConfig();
        if (!cfg.javaPackEnabled()) {
            plugin.getLogger().info("Java pack disabled: resourcepack.java.enabled is false.");
            return;
        }

        if (!stagePackFile()) {
            return;
        }

        String configuredUrl = cfg.javaPackUrl();
        String publicAddress = cfg.javaPackPublicAddress();
        boolean hasUrl = configuredUrl != null && !configuredUrl.isBlank();
        boolean hasSelfHostAddress = publicAddress != null && !publicAddress.isBlank();

        if (hasUrl) {
            try {
                packUri = new URI(configuredUrl);
            } catch (URISyntaxException ex) {
                plugin.getLogger().warning("Java pack disabled: resourcepack.java.url is not a valid URL (" + ex.getMessage() + ").");
                return;
            }
            deliveryMode = DeliveryMode.EXTERNAL;
        } else if (cfg.javaPackSelfHostEnabled() && hasSelfHostAddress) {
            if (!startSelfHostServer(cfg)) {
                return;
            }
            packUri = URI.create("http://" + publicAddress + ":" + cfg.javaPackSelfHostPort() + HTTP_PATH);
            deliveryMode = DeliveryMode.SELF_HOST;
        } else if (!cfg.javaPackSelfHostEnabled()) {
            plugin.getLogger().warning("Java pack disabled: no public URL configured. Set resourcepack.java.url, "
                    + "or enable resourcepack.java.self-host and set self-host.public-address.");
            return;
        } else {
            plugin.getLogger().warning("Java pack disabled: no public URL configured. "
                    + "resourcepack.java.self-host.public-address is required when resourcepack.java.url is blank (see README.md).");
            return;
        }

        enabled = true;
        plugin.getLogger().info("Java pack ready (" + deliveryMode + "): " + packUri + " (sha1 " + sha1Hex + ").");
    }

    private boolean stagePackFile() {
        try {
            plugin.saveResource(EMBEDDED_RESOURCE, true);
            Path extracted = plugin.getDataFolder().toPath().resolve(EMBEDDED_RESOURCE);
            Path staged = plugin.getDataFolder().toPath().resolve(STAGED_FILE_NAME);
            Files.copy(extracted, staged, StandardCopyOption.REPLACE_EXISTING);
            packBytes = Files.readAllBytes(staged);
            sha1Hex = sha1Hex(packBytes);
            return true;
        } catch (IOException | IllegalArgumentException ex) {
            plugin.getLogger().warning("Failed to stage the embedded Java resource pack: " + ex.getMessage());
            return false;
        }
    }

    private boolean startSelfHostServer(ArchFlagsConfig cfg) {
        try {
            InetSocketAddress addr = new InetSocketAddress(cfg.javaPackSelfHostBindAddress(), cfg.javaPackSelfHostPort());
            httpServer = HttpServer.create(addr, 0);
            httpServer.createContext(HTTP_PATH, exchange -> {
                byte[] body = this.packBytes;
                if (body == null) {
                    exchange.sendResponseHeaders(503, -1);
                    exchange.close();
                    return;
                }
                exchange.getResponseHeaders().add("Content-Type", "application/zip");
                exchange.sendResponseHeaders(200, body.length);
                try (OutputStream os = exchange.getResponseBody()) {
                    os.write(body);
                } finally {
                    exchange.close();
                }
            });
            httpServer.setExecutor(Executors.newFixedThreadPool(2, r -> {
                Thread t = new Thread(r, "ArchFlags-PackServer");
                t.setDaemon(true);
                return t;
            }));
            httpServer.start();
            plugin.getLogger().info("Self-hosting the Java resource pack on "
                    + cfg.javaPackSelfHostBindAddress() + ":" + cfg.javaPackSelfHostPort() + HTTP_PATH + ".");
            return true;
        } catch (IOException ex) {
            plugin.getLogger().warning("Failed to start the self-hosted resource pack server: " + ex.getMessage()
                    + " -- is the port already in use? Java resource pack sending disabled.");
            return false;
        }
    }

    /** Sends the pack to a Java player, additively (never replacing NxRanks' own pack). No-op for Bedrock/Floodgate players. */
    public void sendTo(Player player) {
        if (!enabled || packUri == null || sha1Hex == null) {
            return;
        }
        if (plugin.floodgateIntegration().isBedrockPlayer(player.getName(), player.getUniqueId())) {
            return;
        }
        try {
            ArchFlagsConfig cfg = plugin.archConfig();
            ResourcePackInfo info = ResourcePackInfo.resourcePackInfo(PACK_ID, packUri, sha1Hex);
            ResourcePackRequest request = ResourcePackRequest.resourcePackRequest()
                    .packs(info)
                    .replace(false) // additive -- never removes an already-applied pack (e.g. NxRanks')
                    .required(cfg.javaPackRequired())
                    .prompt(LegacyComponentSerializer.legacySection().deserialize(cfg.javaPackPrompt()))
                    .build();
            player.sendResourcePacks(request);
        } catch (Exception ex) {
            if (plugin.archConfig().debug()) {
                plugin.getLogger().warning("Failed to send the Java resource pack to " + player.getName() + ": " + ex.getMessage());
            }
        }
    }

    public void stop() {
        if (httpServer != null) {
            httpServer.stop(0);
            httpServer = null;
        }
    }

    public boolean isEnabled() {
        return enabled;
    }

    public DeliveryMode deliveryMode() {
        return deliveryMode;
    }

    /** Nullable -- null unless {@link #isEnabled()}. Never a secret; it's the pack's public download URL. */
    public URI packUri() {
        return packUri;
    }

    /** Nullable -- the SHA-1 of the currently-staged pack file. Not a secret. */
    public String sha1() {
        return sha1Hex;
    }

    public int selfHostPort() {
        return plugin.archConfig().javaPackSelfHostPort();
    }

    private static String sha1Hex(byte[] data) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-1");
            byte[] hash = digest.digest(data);
            StringBuilder sb = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException("SHA-1 not available", ex);
        }
    }
}
